// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygedaehnnwepxipzvfxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZWRhZWhubndlcHhpcHp2ZnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzOTgzNjIsImV4cCI6MjA3Nzk3NDM2Mn0.83UkkgZGiU75OVYtTOV9SCCpTIjTFys2Sbiw30GMimo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});